apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      role: web
  template:
    metadata:
      labels:
        app: api
        role: web
    spec:
      containers:
      - image: registry.openculinary.org/reciperadar/api
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 8000
        env:
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-contact-mail
                key: username
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-contact-mail
                key: password
